apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: fedora
        image: master.turbot:5000/fedora:24-demo
        imagePullPolicy: Always
        env:
        - name: VERSION
          value: "v1"
