apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - image: busybox:latest
    name: busybox
    command:
    - sh
    - -c
    - "trap \"exit 0\" SIGTERM; while true; do echo $(hostname) $(date); sleep 1; done"
