apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - image: master.turbot:5000/fedora:24-demo
    name: fedora
    imagePullPolicy: Always
    volumeMounts:
    - name: secret
      mountPath: "/mnt"
      readOnly: true
  volumes:
  - name: secret
    secret:
      secretName: demo
