apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kube-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        kubernetes.io/cluster-service: "true"
    spec:
      dnsPolicy: Default
      containers:
      - name: kubedns
# curl -k -s -X GET https://gcr.io/v2/google_containers/kubedns-amd64/tags/list
        image: gcr.io/google_containers/kubedns-amd64:1.5
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        args:
        - --domain=kube.turbot
